package pt.ulisboa.ciencias.di.aw1718.group06.dataaccess;

import java.sql.Connection;
import java.util.List;

public class DiseaseCatalog {

	private Connection conn;
	
	private DiseaseCatalog() {
		// TODO initialize the mysql connection
	}
	
	private static class StaticHolder {
		static final DiseaseCatalog INSTANCE = new DiseaseCatalog();
	}
    
	
	public static DiseaseCatalog getInstance(){
		return StaticHolder.INSTANCE;
	}
	
	
	public List<Disease> getDiseases(){
		//TODO auto generated method stub
		return null;
	}
	
	
	public int addDisease(){
		//TODO auto generated method stub
		//returns the disease id generated by the db
		return 0;
	}
	
	
	public boolean updateDisease(Disease disease){
		//TODO auto generated method stub
		return false;
	}
}
